#!/usr/bin/sh

# Set custom VM resolution
xrandr --newmode "1800x1200_60.00"  180.75  1800 1920 2112 2424  1200 1203 1213 1245 -hsync +vsync
xrandr --addmode Virtual-1 1800x1200_60.00
xrandr -s 1800x1200

# Start-up programs/scripts
~/.config/0touch/configs/eww/eww/target/release/eww daemon
~/.config/0touch/configs/eww/eww/target/release/eww open bar
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
